---
language: ruby
before_install:
  - sudo apt-get update
  - sudo apt-get install default-jre
before_script:
  - jpath=$(which java) && echo "Java path: $jpath"
bundler_args: "--without system"
script: "bundle exec rspec --color --format documentation spec/unit"
notifications:
  email: false
sudo: false
before_install: gem update bundler
rvm:
  - "2.5"
  - "2.4"
  - "2.3"
  - "jruby"
jdk:
    - oraclejdk8
