---
language: ruby
before_install:
  - wget https://download.checkmarx.com/8.8.0/Plugins/CxConsolePlugin-8.80.0.zip
  - unzip CxConsolePlugin-8.80.0.zip
  - chmod +x ./CxConsolePlugin-8.80.0/runCxConsole.sh
bundler_args: "--without system"
#script: "bundle exec rspec --color --format documentation spec/unit"
script: "./CxConsolePlugin-8.80.0/runCxConsole.sh"
notifications:
  email: false
sudo: false
before_install: gem update bundler
rvm:
  - "2.5"
  - "2.4"
  - "2.3"
  - "jruby"
jdk:
    - oraclejdk8
