---
language: ruby
before_install:
  -  gem update bundler
  - mkdir -p $USERDIR
  - wget https://download.checkmarx.com/8.8.0/Plugins/CxConsolePlugin-8.80.0.zip -O $USERDIR/CxPlugin.zip
  - unzip $USERDIR/CxPlugin.zip
  - chmod +x $USERDIR/CxConsolePlugin-8.80.0/runCxConsole.sh
bundler_args: "--without system"
#script: "bundle exec rspec --color --format documentation spec/unit"
script: "$USERDIR/CxConsolePlugin-8.80.0/runCxConsole.sh"
notifications:
  email: false
sudo: false
rvm:
  - "2.5"
  - "2.4"
  - "2.3"
  - "jruby"
jdk:
    - oraclejdk8
env:
  global:
    - USERDIR=/tmp/userdir
