---
language: ruby
before_install:
  -  gem update bundler
  - mkdir -p $USERDIR
  - wget https://download.checkmarx.com/8.8.0/Plugins/CxConsolePlugin-8.80.0.zip -O $USERDIR/CxPlugin.zip
  - unzip $USERDIR/CxPlugin.zip -d $USERDIR
  - chmod +x $USERDIR/CxConsolePlugin-8.80.0/runCxConsole.sh
bundler_args: "--without system"
#script: "bundle exec rspec --color --format documentation spec/unit"
script: 
 - "bundle exec rspec --color --format documentation spec/unit"
 - "$SCAN"
notifications:
  email: false
sudo: false
rvm:
  - "2.5"
  - "2.4"
  - "2.3"
  - "jruby"
jdk:
    - oraclejdk8
env:
  global:
    - USERDIR=/tmp/userdir
  - "SCAN=$USERDIR/CxConsolePlugin-8.80.0/runCxConsole.sh"

matrix:
  exclude:
    - rvm: "2.4"
      env: "SCAN=$USERDIR/CxConsolePlugin-8.80.0/runCxConsole.sh"
    - rvm: "2.3"
      env: "SCAN=$USERDIR/CxConsolePlugin-8.80.0/runCxConsole.sh"
    - rvm: "jruby"
      env: "SCAN=$USERDIR/CxConsolePlugin-8.80.0/runCxConsole.sh"
